In [10]:
import pandas as pd

In [30]:
account_parcels = pd.read_csv('https://raw.githubusercontent.com/UncertainQubit/binder/master/bcdata/Account_Parcels.csv')

In [20]:
buildings = pd.read_csv('https://raw.githubusercontent.com/UncertainQubit/binder/master/bcdata/Buildings.csv', 
                        low_memory=False)

In [21]:
owner_address = pd.read_csv('https://raw.githubusercontent.com/UncertainQubit/binder/master/bcdata/Owner_Address.csv', 
                            low_memory=False)

In [14]:
sales = pd.read_csv('https://raw.githubusercontent.com/UncertainQubit/binder/master/bcdata/Sales.csv')

In [15]:
values = pd.read_csv('https://raw.githubusercontent.com/UncertainQubit/binder/master/bcdata/Values.csv')

In [26]:
account_parcels.head()

      strap      Parcelno
0  M2000001  146318113001
1  M2000002  146318113001
2  M2000003  146321300001
3  M2000004  146318113001
4  M2000007  146318113001

In [35]:
left = account_parcels.set_index('strap')
right = buildings.set_index('strap')

newdf = left.join(right)
newdf.head()

,Parcelno,bld_num,section_num,designCode,designCodeDscr,qualityCode,qualityCodeDscr,bldgClass,bldgClassDscr,ConstCode,...,ExtWallDscrPrim,ExtWallSec,ExtWallDscrSec,IntWall,IntWallDscr,Roof_Cover,Roof_CoverDscr,Stories,UnitCount,status_cd
strap,,,,,,,,,,,,,,,,,,,,,
M2000001,146318113001,1.0,1.0,0320,DOUBLE WIDE,30,AVERAGE,1235.0,MANUFACTURED HOUSING IMPROVEMENTS,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
M2000002,146318113001,1.0,1.0,0310,SINGLE WIDE,30,AVERAGE,1235.0,MANUFACTURED HOUSING IMPROVEMENTS,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
M2000003,146321300001,1.0,1.0,0310,SINGLE WIDE,30,AVERAGE,1235.0,MANUFACTURED HOUSING IMPROVEMENTS,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
M2000004,146318113001,1.0,1.0,0320,DOUBLE WIDE,30,AVERAGE,1235.0,MANUFACTURED HOUSING IMPROVEMENTS,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
M2000007,146318113001,1.0,1.0,0320,DOUBLE WIDE,30,AVERAGE,1235.0,MANUFACTURED HOUSING IMPROVEMENTS,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A

In [48]:
sampledf = buildings.drop(['ExtWallDscrSec', 'UnitCount'], axis=1)
sampledf.describe()

,bld_num,section_num,bldgClass,ConstCode,builtYear,CompCode,EffectiveYear,bsmtSF,carStorageSF,nbrBedRoom,...,nbrFullBaths,nbrHalfBaths,TotalFinishedSF,Ac,Heating,ExtWallPrim,ExtWallSec,IntWall,Roof_Cover,Stories
count,169001.000000,169001.000000,169001.000000,169001.000000,169001.000000,169001.000000,169001.000000,169001.000000,169001.000000,169001.000000,...,169001.000000,169001.000000,169001.000000,70619.000000,150623.000000,146269.000000,46255.000000,145167.000000,83427.000000,18482.000000
mean,1.309986,1.320637,1496.079881,286.332862,1977.546636,0.995696,1985.114419,490.786191,397.322531,3.244046,...,1.771173,0.449959,2319.065230,210.102451,819.706154,31.500215,518.209707,1130.164914,1216.490848,1.210908
std,2.152269,1.971107,1179.594905,91.471119,74.981289,0.054700,72.516602,731.398172,1118.132302,8.139678,...,6.631637,1.350101,7416.225306,1.353575,28.058925,32.869566,31.904037,5.291766,18.466797,0.650235
min,0.000000,1.000000,1210.000000,0.000000,0.000000,0.000000,0.000000,-578.000000,-208.000000,0.000000,...,0.000000,0.000000,0.000000,200.000000,800.000000,0.000000,500.000000,1100.000000,1200.000000,0.000000
25%,1.000000,1.000000,1212.000000,310.000000,1969.000000,1.000000,1977.000000,0.000000,0.000000,2.000000,...,1.000000,0.000000,1034.000000,210.000000,810.000000,10.000000,500.000000,1130.000000,1210.000000,1.000000
50%,1.000000,1.000000,1212.000000,310.000000,1983.000000,1.000000,1990.000000,328.000000,400.000000,3.000000,...,1.000000,0.000000,1538.000000,210.000000,810.000000,10.000000,500.000000,1130.000000,1210.000000,1.000000
75%,1.000000,1.000000,1212.000000,310.000000,1998.000000,1.000000,2000.000000,832.000000,539.000000,4.000000,...,2.000000,1.000000,2275.000000,210.000000,810.000000,40.000000,530.000000,1130.000000,1210.000000,1.000000
max,123.000000,90.000000,9299.000000,420.000000,2020.000000,1.000000,2020.000000,93520.000000,122946.000000,588.000000,...,556.000000,192.000000,543610.000000,220.000000,1000.000000,140.000000,630.000000,1160.000000,1291.000000,13.000000

In [52]:
sampledf = sampledf.dropna(axis=0)
sampledf.describe()

,bld_num,section_num,bldgClass,ConstCode,builtYear,CompCode,EffectiveYear,bsmtSF,carStorageSF,nbrBedRoom,...,nbrFullBaths,nbrHalfBaths,TotalFinishedSF,Ac,Heating,ExtWallPrim,ExtWallSec,IntWall,Roof_Cover,Stories
count,172.000000,172.000000,172.000000,172.000000,172.000000,172.0,172.000000,172.000000,172.000000,172.000000,...,172.000000,172.000000,172.000000,172.0,172.000000,172.000000,172.000000,172.0,172.000000,172.000000
mean,3.837209,3.860465,1317.645349,310.232558,2014.808140,1.0,2015.162791,35.127907,1821.598837,71.133721,...,68.633721,0.151163,48471.401163,210.0,811.802326,37.558140,543.662791,1130.0,1220.523256,2.936047
std,3.322299,3.309256,862.362190,1.858594,7.560543,0.0,5.720304,460.698181,10975.217099,69.837821,...,61.019023,0.741698,38483.255314,0.0,10.012063,13.545336,48.977405,0.0,25.020799,1.065944
min,1.000000,1.000000,1210.000000,310.000000,1960.000000,1.0,1971.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,210.0,810.000000,10.000000,500.000000,1130.0,1210.000000,1.000000
25%,1.750000,2.000000,1225.000000,310.000000,2014.000000,1.0,2014.000000,0.000000,0.000000,0.000000,...,12.000000,0.000000,14328.000000,210.0,810.000000,30.000000,500.000000,1130.0,1210.000000,3.000000
50%,3.000000,3.000000,1225.000000,310.000000,2017.000000,1.0,2017.000000,0.000000,0.000000,47.500000,...,46.000000,0.000000,31686.000000,210.0,810.000000,40.000000,530.000000,1130.0,1210.000000,3.000000
75%,5.000000,5.000000,1225.000000,310.000000,2017.000000,1.0,2017.000000,0.000000,0.000000,152.000000,...,140.000000,0.000000,92218.000000,210.0,810.000000,40.000000,610.000000,1130.0,1210.000000,3.000000
max,14.000000,14.000000,9270.000000,330.000000,2019.000000,1.0,2019.000000,6042.000000,122946.000000,168.000000,...,161.000000,8.000000,108313.000000,210.0,910.000000,120.000000,610.000000,1130.0,1280.000000,11.000000